version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: vitrygtr
      MYSQL_DATABASE: auth_db
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  php_apache:
    image: php:7.4-apache
    container_name: php_apache
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/var/www/html
      - ./backend:/var/www/html/backend
    depends_on:
      - db
    command: >
      bash -c "apt-get update && apt-get install -y libldap2-dev msmtp && docker-php-ext-configure ldap --with-ldap=/usr && docker-php-ext-install ldap && apache2-foreground"
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap_server
    environment:
      LDAP_ORGANISATION: "MyCompany"
      LDAP_DOMAIN: "mycompany.com"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldap:/var/lib/ldap
      - ./ldap_config:/etc/ldap/slapd.d

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: ldap_admin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap_server
    ports:
      - "6443:443"